<h1>
Problema das Rainhas
</h1>

Em um tabuleiro 𝑛×𝑛, uma rainha é colocada em um quadrado, irá dominar todos os quadrados que estiverem na mesma linha, coluna e diagonais. A ideia por trás deste probelma é achar a quantidade mínima de rainhas necessárias para dominar o tabuleiro inteiro. Dominar, neste problema, significa cobrir todos os quadrados possíveis sendo atacados por rainhas incluindo aqueles onde as rainhas se encontram.

Primeiro, vamos começar definindo o tabuleiro como é feito no artigo. Vamos começar por um tabuleiro 4x4, igual começa no artigo:

In [45]:
import numpy as np
N = 8
chessBoard = np.array([x+1 for x in range(N*N)])

chessBoard = chessBoard.reshape(N,N)
chessBoard

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

Agora, criar a função para verificar quadrados do tabuleiro que estão sendo dominados por todas as rainhas e retornar os números que estão sendo dominados:

In [67]:
def dominatedSet(queens, chessBoard, verbose=True):
    S = set()
    N = chessBoard.shape[0]
    for queen in queens:
        i = queen[0]
        j = queen[1]
        queenBox = chessBoard[i,j]
        print("rainha", queen, 'valor: ', queenBox)
        # quadrados dominados na horizontal:
        print(chessBoard[i,:])
        S.update(chessBoard[i,:])
        # quadrados dominados na vertical:
        print(chessBoard[:,j])
        S.update(chessBoard[:,j])
        # diagonal
        for d in range(-N+1,N):
            diag = chessBoard.diagonal(d)
            invertDiag = np.fliplr(chessBoard).diagonal(d)
            if queenBox in diag:
                print(diag)
                S.update(diag)
            if queenBox in invertDiag:
                print(invertDiag)
                S.update(invertDiag)
        # diagonal invertida
       # print(np.fliplr(chessBoard).diagonal(0))
    return S
        
        
    

O código abaixo vai então gerar a área de dominância para uma única rainha na posição (3,3) do tabuleiro, ou também podemos dizer, no valor 28 da matriz. 

<b>Para ficar mais claro, o número do quadrado em que a rainha se encontra nós vamos chamar de posição numérica. Então o quadrado 28, em que essa rainha se encontra, é sua posição numérica. A dupla (3,3) e todas as outras nós vamos chamar de posição cartesiana </b>

In [68]:
queens = [(0,0)]

S = dominatedSet([(3,3)], chessBoard)
print(S)

rainha (3, 3) valor:  28
[25 26 27 28 29 30 31 32]
[ 4 12 20 28 36 44 52 60]
[ 1 10 19 28 37 46 55 64]
[ 7 14 21 28 35 42 49]
{1, 4, 7, 10, 12, 14, 19, 20, 21, 25, 26, 27, 28, 29, 30, 31, 32, 35, 36, 37, 42, 44, 46, 49, 52, 55, 60, 64}


A função que mede o quão próximo estamos de uma boa solução no artigo é dada por:

$ f(x) = {|S| \div |G|}  $

Nesta função, se o resultado for menor que 1, temos que existem alguns ou pelo menos 1 quadrado que não está numa área de dominância das rainhas. Se for 1, significa que as rainhas dominaram todos os quadrados do tabuleiro. 

No código, calcularemos essa função assim:

In [69]:
len(S)/ (N*N) 

0.4375

<h2>Codificação dos indivíduos </h2>

O conjunto de indivíduos será representado por uma matriz onde cada linha é um solução candidata e as colunas são posições das rainhas no tabuleiro para aquela solução. As posições das rainhas serão dadas pelos valores das posições numéricas definidas como um binário de 8 dígitos.
Seria Assim:


In [80]:
rainha1 = format(23,'08b')
rainha2 = format(43,'08b')
rainha3 = format(12,'08b')
rainha4 = format(10,'08b')

np.matrix([[rainha1, rainha2], [rainha3, rainha4]])

matrix([['00010111', '00101011'],
        ['00001100', '00001010']], dtype='<U8')

No caso, a primeira solução candidata tem as rainhas nas posições numéricas 23 e 43, e segunda solução candidata tem rainhas nas posições 12 e 10

<h2>Geração inicial de indivíduos </h2>

A primeira geração consiste de 100 indivíduos (soluções candidatas) geradas aleatoriamente, mantendo a certeza de que em cada possível solução as rainhas estão em posições diferentes. Vamos fazer uma função que faz isso. A função vai receber como parâmetro o número de rainhas que queremos para as soluções possíveis e a dimensão do tabuleiro.

In [168]:
from random import seed
from random import randint

seed(3)

value = randint(0, N*N)
value

def gen_individuals(n_queens, N): 
    A = np.empty((1,2), dtype='str')
    for i in range (0,100):
        set = {}
        newRow = []
        for j in range (0,2):
            randVal = randint(1,N*N)
            while randVal in set: 
                randVal = randint(1,N*N)
                print(randVal)
            randInBin = format(randVal,'08b')
            newRow.append(randInBin)
        A = np.vstack([A, newRow])
    # apaga a primeira linha que é gerada na inicialização da matriz
    A = np.delete(A,0, 0)
    return A



[['00010001' '00110000']
 ['00111101' '00001001']
 ['00000010' '00111101']
 ['00100010' '00011110']
 ['00011001' '00111101']
 ['00111101' '00110011']
 ['00010100' '00011110']
 ['00010100' '00110010']
 ['00000010' '00001001']
 ['00010101' '00000110']
 ['00100111' '00000100']
 ['00100011' '00111101']
 ['00110010' '00110111']
 ['00110011' '00111001']
 ['00010010' '00101111']
 ['00001101' '00000101']
 ['00010010' '01000000']
 ['00011100' '00100010']
 ['00111000' '00100111']
 ['00110110' '00110010']
 ['00101101' '00110101']
 ['00011110' '00101100']
 ['00000100' '00100100']
 ['00010101' '00101010']
 ['00001110' '00011100']
 ['00100011' '00100101']
 ['00010000' '00001001']
 ['00111110' '00111110']
 ['00001100' '00101101']
 ['00001001' '00110101']
 ['00010100' '00000011']
 ['00100110' '00110111']
 ['00110110' '00010000']
 ['00000110' '00000110']
 ['00110001' '00101011']
 ['00100100' '00011111']
 ['00000101' '00101000']
 ['00000001' '00001010']
 ['00001110' '00000101']
 ['00011010' '00110101']


In [169]:
A = gen_individuals(2,N)
print(A)


[['00000011' '00110101']
 ['00000111' '00001111']
 ['00101100' '00010001']
 ['00100001' '00111110']
 ['00001000' '00101110']
 ['00011101' '00011010']
 ['00010000' '00010000']
 ['00010110' '00011111']
 ['00100100' '00010001']
 ['00000001' '00111111']
 ['00110100' '00000111']
 ['00100011' '00100000']
 ['00100011' '00110111']
 ['00000111' '00111101']
 ['00101010' '00000001']
 ['00001000' '00010001']
 ['00000110' '00010000']
 ['00000111' '00001001']
 ['00111110' '00000101']
 ['00001100' '00111111']
 ['00101001' '00010101']
 ['00101001' '00001010']
 ['00101101' '00110010']
 ['00110010' '00100111']
 ['00101111' '00100010']
 ['00011001' '00101011']
 ['00110111' '00010000']
 ['00010001' '00000001']
 ['00110001' '00001011']
 ['00010111' '00000110']
 ['00110000' '00111011']
 ['00110001' '00000110']
 ['00111000' '00000111']
 ['00110000' '01000000']
 ['00101001' '00110110']
 ['00110110' '00111011']
 ['00000011' '00100000']
 ['00011100' '00100011']
 ['00001010' '00110111']
 ['00011101' '00110111']
