<h1>
Problema das Rainhas
</h1>

Em um tabuleiro 𝑛×𝑛, uma rainha é colocada em um quadrado, irá dominar todos os quadrados que estiverem na mesma linha, coluna e diagonais. A ideia por trás deste probelma é achar a quantidade mínima de rainhas necessárias para dominar o tabuleiro inteiro. Dominar, neste problema, significa cobrir todos os quadrados possíveis sendo atacados por rainhas incluindo aqueles onde as rainhas se encontram.

Primeiro, vamos começar definindo o tabuleiro como é feito no artigo. Vamos começar por um tabuleiro 4x4, igual começa no artigo:

In [12]:
import numpy as np
N = 8
chessBoard = np.array([x+1 for x in range(N*N)])

chessBoard = chessBoard.reshape(N,N)
chessBoard

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

Agora, criar a função para verificar quadrados do tabuleiro que estão sendo dominados por todas as rainhas e retornar os números que estão sendo dominados:

In [20]:
def dominatedSet(queens, chessBoard, verbose=True):
    S = set()
    N = chessBoard.shape[0]
    for queen in queens:
        print("rainha", queen)
        i = queen[0]
        j = queen[1]
        queenBox = chessBoard[i,j]
        # quadrados dominados na horizontal:
        print(chessBoard[i,:])
        S.update(chessBoard[i,:])
        # quadrados dominados na vertical:
        print(chessBoard[:,j])
        S.update(chessBoard[:,j])
        # diagonal
        for d in range(-N+1,N):
            diag = chessBoard.diagonal(d)
            invertDiag = np.fliplr(chessBoard).diagonal(d)
            if queenBox in diag:
                print(diag)
                S.update(diag)
            if queenBox in invertDiag:
                print(invertDiag)
                S.update(invertDiag)
        # diagonal invertida
       # print(np.fliplr(chessBoard).diagonal(0))
    return S
        
        
    

In [22]:
queens = [(0,0)]

S = dominatedSet([(3,0),(3,3)], chessBoard)
print(S)

rainha (3, 0)
[25 26 27 28 29 30 31 32]
[ 1  9 17 25 33 41 49 57]
[25 34 43 52 61]
[ 4 11 18 25]
rainha (3, 3)
[25 26 27 28 29 30 31 32]
[ 4 12 20 28 36 44 52 60]
[ 1 10 19 28 37 46 55 64]
[ 7 14 21 28 35 42 49]
{1, 4, 7, 9, 10, 11, 12, 14, 17, 18, 19, 20, 21, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 41, 42, 43, 44, 46, 49, 52, 55, 57, 60, 61, 64}
